local MOVEMENT_SPEED = 500

function init(self)
	-- make sure our direction is always normalized
	self.dir = vmath.rotate(go.get_rotation(), vmath.vector3(1, 0, 0))
end

function update(self, dt)
	local pos = go.get_position()
	go.set_position(pos + (self.dir * MOVEMENT_SPEED * dt))
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		go.delete()
	end
end
